/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

import dao.CursoDAO;
import modelo.Curso;

public class CadastrarCursoFrame extends javax.swing.JFrame {

    private JTextField txtCodigo;
    private JTextField txtNome;
    private JTextField txtCargaHoraria;

    public CadastrarCursoFrame() {
        setTitle("Cadastrar Curso ou Aluno");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel painel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblCodigo = new JLabel("Código:");
        JLabel lblNome = new JLabel("Nome:");
        JLabel lblCargaHoraria = new JLabel("Carga Horária (horas):");

        txtCodigo = new JTextField(20);
        txtNome = new JTextField(20);
        txtCargaHoraria = new JTextField(20);

        JButton btnConfirmar = new JButton("Confirmar");
        JButton btnCancelar = new JButton("Cancelar");

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.0;
        painel.add(lblCodigo, gbc);

        gbc.gridx = 1;
        gbc.weightx = 1.0;
        painel.add(txtCodigo, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        painel.add(lblNome, gbc);

        gbc.gridx = 1;
        gbc.weightx = 1.0;
        painel.add(txtNome, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.0;
        painel.add(lblCargaHoraria, gbc);

        gbc.gridx = 1;
        gbc.weightx = 1.0;
        painel.add(txtCargaHoraria, gbc);

        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 0.0;
        painel.add(btnConfirmar, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.0;
        painel.add(btnCancelar, gbc);

        btnConfirmar.addActionListener(e -> confirmarCadastro());
        btnCancelar.addActionListener(e -> dispose());

        add(painel);
    }

    private void confirmarCadastro() {
        String codigo = txtCodigo.getText().trim();
        String nome = txtNome.getText().trim();
        String carga = txtCargaHoraria.getText().trim();

        if (codigo.isEmpty() || nome.isEmpty() || carga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nome.length() < 3) {
            JOptionPane.showMessageDialog(this, "O nome deve ter no mínimo 3 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int cargaHoraria;
        try {
            cargaHoraria = Integer.parseInt(carga);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Carga horária deve ser um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cargaHoraria < 20) {
            JOptionPane.showMessageDialog(this, "A carga horária deve ser de no mínimo 20 horas.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int cod = Integer.parseInt(txtCodigo.getText().trim());
        
        Curso curso = new Curso(cod, nome, cargaHoraria, true);
        CursoDAO dao = new CursoDAO();
        dao.adicionarCurso(curso);

        JOptionPane.showMessageDialog(this, "Curso cadastrado com sucesso!\n(Código: " + cod + ", Nome: " + nome + ", Carga Horária: " + cargaHoraria + " horas)");
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCursoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
